/**
 * Central security utilities for client-side safety.
 * These supplement (not replace) server-side validation.
 */

/**
 * Cryptographically secure random ID using Web Crypto API.
 * Replaces Math.random()-based IDs for peer/session identifiers.
 */
export function secureId(prefix = 'id') {
  const buf = new Uint8Array(8);
  crypto.getRandomValues(buf);
  const hex = Array.from(buf).map(b => b.toString(16).padStart(2, '0')).join('');
  return `${prefix}_${Date.now()}_${hex}`;
}

/**
 * Validates that a URL is safe to load (http/https only).
 * Blocks javascript:, data:, blob:, file:, vbscript: and other injection vectors.
 */
export function isSafeUrl(url) {
  if (!url || typeof url !== 'string') return false;
  const trimmed = url.trim();
  if (trimmed.length > 2048) return false; // reject absurdly long URLs
  try {
    const parsed = new URL(trimmed);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}

/**
 * Clamps a string to a maximum length and removes null bytes.
 */
export function clampStr(str, maxLen) {
  if (typeof str !== 'string') return '';
  return str.replace(/\0/g, '').slice(0, maxLen);
}

/**
 * Validates that a WebRTC peer ID was generated by our secureId function.
 * Rejects arbitrary strings that could be injected via signaling.
 */
export function isValidPeerId(id) {
  if (typeof id !== 'string') return false;
  // Must match: prefix_timestamp(13 digits)_hex(16 chars)
  return /^peer_\d{13}_[0-9a-f]{16}$/.test(id);
}

/**
 * Validates that a signaling message payload does not contain
 * fields that would overwrite our own routing fields.
 */
export function sanitizeSignalPayload(payload) {
  if (!payload || typeof payload !== 'object') return {};
  const { room_id, from_peer, to_peer, signal_type, created_at, ...safe } = payload;
  return safe;
}

/**
 * Per-key client-side rate limiter.
 * Prevents accidental or intentional API spam from a single browser session.
 */
export class RateLimiter {
  constructor(minIntervalMs) {
    this._interval = minIntervalMs;
    this._last = new Map();
  }

  allow(key = 'default') {
    const now = Date.now();
    const last = this._last.get(key) || 0;
    if (now - last < this._interval) return false;
    this._last.set(key, now);
    return true;
  }
}

/**
 * Returns a safe image src: validates the URL and falls back to null if unsafe.
 * Use as: <img src={safeSrc(url) || fallback} />
 */
export function safeSrc(url) {
  return isSafeUrl(url) ? url : null;
}

// ── Vault Pro: AES-256-GCM envelope encryption ────────────────────────────
// Used to protect stream keys and API credentials stored in state / IndexedDB.
// Key is derived per-session from a 256-bit secret never persisted to disk.

let _vaultKey = null;

async function getVaultKey() {
  if (_vaultKey) return _vaultKey;
  const raw = crypto.getRandomValues(new Uint8Array(32));
  _vaultKey = await crypto.subtle.importKey(
    'raw', raw, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']
  );
  return _vaultKey;
}

/**
 * Encrypts a plain-text stream key or credential string.
 * Returns a base64url-encoded payload: `<iv>.<ciphertext>` (both base64url).
 */
export async function encryptStreamKey(plaintext) {
  if (typeof plaintext !== 'string') throw new TypeError('plaintext must be a string');
  const key = await getVaultKey();
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const encoded = new TextEncoder().encode(plaintext);
  const cipher = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoded);
  const toB64 = buf => btoa(String.fromCharCode(...new Uint8Array(buf)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  return `${toB64(iv)}.${toB64(cipher)}`;
}

/**
 * Decrypts a payload produced by encryptStreamKey().
 * Returns the original plain-text string, or throws on tampering.
 */
export async function decryptStreamKey(payload) {
  if (typeof payload !== 'string') throw new TypeError('payload must be a string');
  const [ivB64, cipherB64] = payload.split('.');
  if (!ivB64 || !cipherB64) throw new Error('Invalid vault payload format');
  const fromB64 = s => Uint8Array.from(
    atob(s.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0)
  );
  const key = await getVaultKey();
  const plain = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: fromB64(ivB64) },
    key,
    fromB64(cipherB64)
  );
  return new TextDecoder().decode(plain);
}

/** Max lengths for user-generated content fields */
export const LIMITS = {
  CHAT_MESSAGE: 500,
  DISPLAY_NAME: 80,
  ROOM_TITLE: 120,
  JOIN_MESSAGE: 140,
  DENY_REASON: 200,
  VIDEO_URL: 2048,
  MAX_PEERS: 20,
  TRANSLATE_BATCH: 20,  // max messages per LLM translation call
  REACTION_BUFFER: 40,  // max floating reactions rendered at once
  BATTLE_COOLDOWN_MS: 2000,  // min ms between battle tier awards per user
};
